# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the OS, Python version, and dependencies
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

# Python configuration
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

# Additional formats (optional - remove if you don't want PDF/EPUB)
formats:
  - pdf
  - epub
