# Generated by Django 5.2.6 on 2025-09-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaskedRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role_name", models.CharField(default="masked_reader", max_length=64, unique=True)),
                (
                    "inherits_from",
                    models.CharField(
                        default="postgres", help_text="Parent role to inherit permissions from", max_length=64
                    ),
                ),
                ("is_applied", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["role_name"],
            },
        ),
        migrations.CreateModel(
            name="MaskingLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("init", "Extension Initialization"),
                            ("apply", "Rules Applied"),
                            ("drop", "Rules Dropped"),
                            ("dump", "Anonymous Dump Created"),
                            ("static_mask", "Static Masking Applied"),
                            ("role_create", "Masked Role Created"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(default=dict, help_text="JSON details about the operation")),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("user", models.CharField(blank=True, max_length=150)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MaskingRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("table_name", models.CharField(help_text="Database table name", max_length=128)),
                ("column_name", models.CharField(help_text="Column to mask", max_length=128)),
                (
                    "function_expr",
                    models.CharField(
                        help_text='Anonymization function (e.g., "anon.fake_email()" or "anon.partial({col}, 2, \'***\', 2)")',
                        max_length=512,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, help_text="Internal notes about this rule")),
                (
                    "depends_on_unique",
                    models.BooleanField(default=False, help_text="Column has UNIQUE constraint - may cause conflicts"),
                ),
                (
                    "performance_heavy",
                    models.BooleanField(default=False, help_text="Function is computationally expensive"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("applied_at", models.DateTimeField(blank=True, help_text="When rule was last applied", null=True)),
            ],
            options={
                "ordering": ["table_name", "column_name"],
                "unique_together": {("table_name", "column_name")},
            },
        ),
        migrations.CreateModel(
            name="MaskingPreset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "preset_type",
                    models.CharField(
                        choices=[
                            ("django_auth", "Django Auth User"),
                            ("ecommerce", "E-commerce"),
                            ("finance", "Financial Data"),
                            ("healthcare", "Healthcare/Medical"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rules", models.ManyToManyField(blank=True, to="django_postgres_anon.maskingrule")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
